# Generated by Django 5.1.8 on 2025-04-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100, unique=True, verbose_name='Número do Edital')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('data_publicacao', models.DateField(verbose_name='Data de Publicação')),
                ('data_limite_submissao', models.DateField(verbose_name='Data Limite para Submissão')),
            ],
        ),
    ]
