# Generated by Django 5.1.8 on 2025-04-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editais', '0002_convenio_edital_convenio'),
    ]

    operations = [
        migrations.AddField(
            model_name='edital',
            name='liberar_cadastro',
            field=models.BooleanField(default=False, verbose_name='Liberar Cadastro de Projetos'),
        ),
    ]
