# Generated by Django 5.1.8 on 2025-08-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_professor',
            field=models.BooleanField(default=False, help_text='Indica se o usuário é um professor'),
        ),
    ]
